[package]
name = "rust-gitpod"
version = "0.1.0"
authors = ["Anand Aravindan <anand.anand84@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bigdecimal = {verison = "0.2.0", features=["serde"]}
rand = "*"